import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>DOGWISE - O Doguinho sábio da internet</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <Link href="/conselho" ><a className="linkGerar">Pensamento diário do Doguinho</a></Link>
      </div>

    </div>
  )
}
